module Chat
{
	interface User
	{
		void receive(in string author, in string message);
	};

	interface Server
	{
		boolean register(in User u, in string name);
		void quit(in User u);
		void send(in User u, in string message);
	};
};
