module Chat
{
	interface User
	{
		oneway void receive(in string author, in string message);
	};

	interface Server
	{
		boolean register(in User u, in string name);
		oneway void quit(in User u);
		oneway void send(in User u, in string message);
	};
};
